# Generated by Django 5.0.3 on 2024-03-07 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='counter',
            name='nome',
            field=models.CharField(default='contaVisite', max_length=200),
        ),
    ]
