# Generated by Django 5.0.3 on 2024-03-07 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contapp', '0002_counter_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counter',
            name='nome',
            field=models.CharField(default='contaVisite', max_length=200, unique=True),
        ),
    ]
