# Generated by Django 5.0.3 on 2024-03-07 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contapp', '0003_alter_counter_nome'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebPageTxt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
